# Generated by Django 4.2.19 on 2025-03-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="understatplayer",
            name="public_id",
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="understatteamresult",
            name="public_id",
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="understatteamsituation",
            name="public_id",
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
