# Generated by Django 4.2.19 on 2025-03-04 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="understatteamresult",
            name="public_id",
            field=models.IntegerField(unique=True),
        ),
    ]
