# Generated by Django 4.2.19 on 2025-03-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0002_alter_understatteamresult_public_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="understatteamresult",
            name="seaspon",
            field=models.IntegerField(null=True),
        ),
    ]
