# Generated by Django 4.2.19 on 2025-03-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0002_alter_understatplayer_public_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="understatteamsituation",
            name="against_xG",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="understatteamsituation",
            name="xG",
            field=models.FloatField(),
        ),
    ]
