# Generated by Django 4.2.19 on 2025-03-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0003_alter_understatteamsituation_against_xg_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="understatplayer",
            name="public_id",
            field=models.CharField(editable=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="understatteamresult",
            name="public_id",
            field=models.CharField(editable=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="understatteamsituation",
            name="public_id",
            field=models.CharField(editable=False, max_length=20, null=True),
        ),
    ]
