# Generated by Django 4.2.19 on 2025-03-04 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0003_understatteamresult_seaspon"),
    ]

    operations = [
        migrations.RenameField(
            model_name="understatteamresult",
            old_name="seaspon",
            new_name="season",
        ),
    ]
