# Generated by Django 4.2.19 on 2025-03-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0004_rename_seaspon_understatteamresult_season"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnderstatTeamSituation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("team", models.CharField(max_length=50)),
                ("source", models.CharField(max_length=20)),
                ("shots", models.IntegerField()),
                ("goals", models.IntegerField()),
                ("xG", models.IntegerField()),
                ("against_shots", models.IntegerField()),
                ("against_goals", models.IntegerField()),
                ("against_xG", models.IntegerField()),
                ("percent_shots_made", models.FloatField()),
                ("percent_against_shots_made", models.FloatField()),
            ],
        ),
    ]
