# Generated by Django 4.2.19 on 2025-03-04 13:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0004_alter_understatplayer_public_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnderstatTeamFormationStats",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "public_id",
                    models.CharField(editable=False, max_length=50, null=True),
                ),
                ("season", models.IntegerField(default=2025)),
                ("team", models.CharField(max_length=50)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("source", models.CharField(max_length=20)),
                ("time_spent", models.IntegerField()),
                ("shots", models.IntegerField()),
                ("goals", models.IntegerField()),
                ("xG", models.FloatField()),
                ("against_shots", models.IntegerField()),
                ("against_goals", models.IntegerField()),
                ("against_xG", models.FloatField()),
                ("percent_shots_made", models.FloatField()),
                ("percent_against_shots_made", models.FloatField()),
            ],
            options={
                "ordering": ["-date_created"],
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="understatplayer",
            name="public_id",
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="understatteamresult",
            name="public_id",
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="understatteamsituation",
            name="public_id",
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
    ]
