# Generated by Django 4.2.19 on 2025-03-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0005_understatteamformationstats_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="understatteamformationstats",
            name="percent_against_shots_made_across_all_goals",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="understatteamformationstats",
            name="percent_shots_made_across_all_goals",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="understatteamsituation",
            name="percent_against_shots_made_across_all_goals",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="understatteamsituation",
            name="percent_shots_made_across_all_goals",
            field=models.FloatField(null=True),
        ),
    ]
