# Generated by Django 4.2.19 on 2025-03-05 06:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0007_understatteamtimingstats"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnderstatTeamPlayerStats",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "public_id",
                    models.CharField(editable=False, max_length=50, null=True),
                ),
                ("season", models.IntegerField(default=2025)),
                ("team", models.CharField(max_length=50)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("player_name", models.CharField(max_length=100)),
                ("lowercase_player_name", models.CharField(max_length=100)),
                ("games", models.IntegerField()),
                ("time", models.IntegerField()),
                ("goals", models.IntegerField()),
                ("xG", models.FloatField()),
                ("assists", models.IntegerField()),
                ("xA", models.FloatField()),
                ("shots", models.IntegerField()),
                ("key_passes", models.IntegerField()),
                ("yellow_cards", models.IntegerField()),
                ("red_cards", models.IntegerField()),
                ("position", models.CharField(max_length=50)),
                ("npg", models.IntegerField()),
                ("npxG", models.FloatField()),
                ("xGChain", models.FloatField()),
                ("xGBuildup", models.FloatField()),
            ],
            options={
                "ordering": ["-date_created"],
                "abstract": False,
            },
        ),
    ]
