# Generated by Django 4.2.19 on 2025-03-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0008_understatteamplayerstats"),
    ]

    operations = [
        migrations.AddField(
            model_name="understatteamplayerstats",
            name="percent_shots_made_across_all_goals",
            field=models.FloatField(null=True),
        ),
    ]
